### ISSUE TITLE
Help Wanted - What's missing?

### ISSUE THREAD

**Issue by andyruth** [awsdocs/aws-marketplace-user-guide-for-sellers#1]
Have you ever looked at the user guide hoping to find content on a topic and not found it, or found it was confusing or didn't give you enough information to make a decision and take action? Do you have tips and tricks you would like to see added to the user guide for AWS Marketplace?

Please share your requests for content, ideas, or suggested changes. 

Thanks,
Andy Ruth
Senior Technical Writer
AWS Marketplace
https://docs.aws.amazon.com/marketplace/latest/userguide/

**Comment by andyruth** [comment]
I'll leave that up to you. I'm happy to take comments and make changes based on the comments.

**Comment by lestephane** [comment]
@andyruth Entered #8 some time ago, still waiting on feedback as to whether this is an OK practice.
To further support the (currently non-existing) continuous integration support for marketplace portals, i now entered #10 and #11 as well. I hope you'll give it some consideration, or at least pass it on to the powers that be. I cannot develop a portal that i'm unable to run test cases against, end-to-end. Regards

**Comment by andyruth** [comment]
@lestephane Sorry for the slow response, I've had my head turned in a different direction. I've reached out to my dev teams and will let you know as soon as I can.
