### ISSUE TITLE
Triggering the x-amzn-marketplace-token request in a CI scenario

### ISSUE THREAD

**Issue by lestephane** [awsdocs/aws-marketplace-user-guide-for-sellers#10]
Today, if I want to test a portal I'm developing locally on my machine, I can probably have amazon issue the x-amzn-marketplace-token request to my local installation (see: https://github.com/awsdocs/aws-marketplace-user-guide-for-sellers/issues/8, waiting on feedback there). I would then have to trigger the request manually, by logging in using a amazon test account, and clicking subscribe for the related product in the marketplace. 

In a continuous integration scenario, given that the token is opaque and generated by amazon, when running an automated test, the triggering of the  x-amzn-marketplace-token request requires the spawning of a headless browser, logging in using the stored credentials of the amazon test account, clicking subscribe in the marketplace.

Is that the only way? Is there no simpler (api) way to generate the token based on the stored credentials of the amazon test account?

**Comment by lestephane** [comment]
I was given half of the answer by @dylanrush in https://github.com/awsdocs/aws-marketplace-user-guide-for-sellers/issues/8#issuecomment-457319507

But that leaves the other half unanswered: How do I get a marketplace registration token? This is one of the required argument in the `SaaSBillingRegistrationTester.html` form mentioned in the comment.

In order to get that marketplace registration token, I really want to avoid spawning a full browser and simulating a user logging in, going to the product page, and clicking subscribe (which will take way too long). Remember, this issue is about a CI, automated testing scenario, where headless rules, and time is (literally) money.

From looking at Firefox Debug console, I see that the browser gets the registration token from issuing a request to 

```bash
https://aws.amazon.com/marketplace/saas/fulfillment/saas/setup?productId=(product listing id)
```
With _a lot_ of `x-amz-*` headers and `aws-*` cookies. 

Now all I need is a CI-friendly way to invoke that URL with the right arguments. 

Surely, there's a headless way to get the registration token?

**Comment by andyruth** [comment]
Unfortunately there isn't. I've asked the dev team about putting it on their backlog so it is on their radar anyway.

**Comment by lestephane** [comment]
Just so you know, it takes 35 seconds to go through the whole process using my automation script.
This impacts the ability to run automated tests against a SaaS product portal.
