### ISSUE TITLE
Is ResolveCustomer idempotent?

### ISSUE THREAD

**Issue by lestephane** [awsdocs/aws-marketplace-user-guide-for-sellers#11]
Assuming
1. a user suscribes to a marketplace product
2. later unsubscribes from that same marketplace product
3. later subscribes again to that same marketplace product

Does the ResolveCustomer call in 1. and 3. return the exact
same pair of CustomerIdentifier + ProductCode?

**Comment by dylanrush** [comment]
Yes, ResolveCustomer will return the exact same CustomerIdentifier + ProductCode pair if the customer unsubscribes then re-subscribes.

**Comment by lestephane** [comment]
Thanks
