### ISSUE TITLE
Sample policy doesn't grant access to CAS

### ISSUE THREAD

**Issue by mblanchard23** [awsdocs/aws-marketplace-user-guide-for-sellers#2]
Adding the sample policy to a user doesn't seem to allow access to Marketplace Reports / CAS enrollment

```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": [
            "iam:Generate*",
            "iam:Get*",
            "iam:List*",
            "iam:Simulate*"
            ],
            "Resource": "arn:aws:iam::123456789123:user/goldmine-test-seller-with-customer-support-policy"
            }
            ]
        }
```

**Comment by andyruth** [comment]
Sorry it isn't working for you. Let me research to see if I can find out what is going on. Did you cut-and-paste this code or write it yourself?

**Comment by mblanchard23** [comment]
Sorry - grabbed it from the docs here:

https://github.com/awsdocs/aws-marketplace-user-guide/blob/master/doc_source/commerce-analytics-service.md#configure-aws-account-permissions

**Comment by mblanchard23** [comment]
Not sure if that policy above is helpful or if I misunderstood. I was under the impression it would delegate permissions to an IAM user to enroll in CAS and use generate-data-set

There should also probably also be a reference to marketplacecommerceanalytics:GenerateDataSet somewhere in the doc as it's required to run any of the test cases, something along the lines of

```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": "marketplacecommerceanalytics:*",
            "Resource": "arn:aws:iam::12344567890:user/your-reporting-user"
        }
    ]
}
```

**Comment by andyruth** [comment]
good point. Right now our IAM permissions content is distributed and I am not sure that is the best approach. I am working on consolidating all of the security content. With IAM specifically, there are dependencies to have permissions that are not specific to the feature. For instance, to view reports requires permissions specific to viewing reports, but if you are viewing them through AMMP, you have to have read permissions on AMMP.
