### ISSUE TITLE
SaaS Contract Guide doesn't mention us-east-1 availability

### ISSUE THREAD

**Issue by mikemorain** [awsdocs/aws-marketplace-user-guide-for-sellers#3]
The SaaS Contract section of the guide is missing a note to let developers know where the API is available. Without this note, it is confusing, because the Metering Service requires users to integration in-region.

I will add a note and submit a pull request shortly.

**Comment by andyruth** [comment]
thanks!

**Comment by mikemorain** [comment]
No problem! Let me know if there is anything you need further with regards to the fixes in the pull request.

**Comment by andyruth** [comment]
nope. I merged.

**Comment by andyruth** [comment]
merged
