### ISSUE TITLE
Please add a version history to the AWS Marketplace User Guide

### ISSUE THREAD

**Issue by lestephane** [awsdocs/aws-marketplace-user-guide-for-sellers#6]
If you fix any documentation issue, there is no way for someone to tell in which version it was fixed or whether the user guide pdf they're looking at contains the fix. More broadly, if you and I have a copy of the PDF, there is no way for us to tell whether we're talking about the same version.

I suggest adding a version history table, and including, every time a commit fixes an issue with the documentation, the version of the document that the issue is fixed in.

An added bonus is that people reporting issues against the documentation can specify the version of the document they are referring to, allowing you to cut down of false positives (issues that have already been fixed in a later version of the document).

**Comment by andyruth** [comment]
Good point. I've added a doc history to the table of contents. Right now we hit big changes (adding new content or major structural changes) but not the little ones. Do you think that will work, or should I consider documenting every  change?

**Comment by lestephane** [comment]
My suggestion is as follows:

- Create a Git tag every time a releasable set of changes has happened (no
inconsistencies or major open issues)
- Add in the version history table in the pdf an entry with
  - the git tag name
  - the date the tag was created
  - a one-line description
  - a link to the GitHub diff between that tag and the previous one.

If you do this, and only publish a new version of the pdf when there is a
new tag, this should
- ensure I don't see an inconsistent version of the document
- give me a way to answer the question 'What has changed' since I looked at
the PDF x weeks ago.

If you add a version history entry only when you add a tag, the version
history table will not be too verbose (i can always drill down by clicking
the GitHub diff link).
And if there are too many tags, move the version history to an appendix at
the end of the document, so it can grow without obscuring the rest of the
document.

Cheers
Stephane
