### ISSUE TITLE
There is no link to the aws reference implementation of an api developer portal 

### ISSUE THREAD

**Issue by lestephane** [awsdocs/aws-marketplace-user-guide-for-sellers#7]
If a developer wants to develop an API product to be offered on the AWS Marketplace, and the user guide is not enough to understand the finer details of what's really required, the developer will land sooner or later on the [aws-api-gateway-developer-portal github project.](https://github.com/awslabs/aws-api-gateway-developer-portal) 

In order to make it easier for people to find the reference implementation, it should be linked to from the user guide. Right now, it isn't:

![image](https://user-images.githubusercontent.com/5460884/47961382-af4ea480-e012-11e8-9b08-191f858c078e.png)

Disclaimer: I have the user guide and the aws-api-gateway-developer-portal cloned locally, and I still am trying to triangulate all the parts of the puzzle. And even when I do, if I don't get to work on that part of our system for another month or two, I forget what I've learned and need to start from the beginning. So this kind of linking is not a luxury.

**Comment by andyruth** [comment]
working on where to add it now.

**Comment by awsdan** [comment]
Thanks, I'm updating the docs to add this.
