### ISSUE TITLE
Format "new customer" code sample

### ISSUE THREAD

**Issue by matthewkmayer** [awsdocs/aws-marketplace-user-guide-for-sellers#9]
In https://github.com/awsdocs/aws-marketplace-user-guide-for-sellers/blob/master/doc_source/configuring-your-saas-application-to-accept-new-customers.md there is a sample for calling `ResolveCustomer`. The Python sample code is missing indentation so it's difficult to follow what it's doing.

I'd love to see the code indented and it'd be mega-awesome to have syntax highlighting. 🤘

**Comment by awsdan** [comment]
Updating this, thanks for the request!
